[package]
org = "ballerinax"
name = "snowflake"
version = "1.2.1"
authors = ["Ballerina"]
keywords = ["IT Operations/Cloud Services", "Cost/Paid"]
repository = "https://github.com/ballerina-platform/module-ballerinax-snowflake"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "snowflake-native"
version = "1.2.1"
path = "../native/build/libs/snowflake-native-1.2.1.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.10.0"
path = "./lib/sql-native-1.10.0.jar"
